### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PyCharm

###
GET http://127.0.0.1:8000
###
GET http://127.0.0.1:8000/docs
###
GET http://127.0.0.1:8000/api/posts
###